#!/usr/bin/env python3
"""Render the Flipside self-pitch deck to PNGs with headless Chrome.

Reads  ../deck.json, ../fallback-deck.json and ../../brand/tokens.json (+ mark SVGs)
Writes ./brand.css (generated from tokens.json; edit tokens, not this file)
       ../slides/{1200x630,2400x1260}/NN-id.png
       ../notes/800x600/NN-id.png
       ../fallback/slides/..., ../fallback/notes/...
       ../contact-sheet.png
Keeps  ./html/ (intermediate pages, handy for tweaking CSS)

Python standard library plus Google Chrome. Fonts are embedded from ./fonts.
"""
import base64
import html
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
DECK = HERE.parent
ROOT = DECK.parent
BRAND = ROOT / "brand"
CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
PROFILE = Path(tempfile.mkdtemp(prefix="flipside-chrome-"))  # throwaway, removed at exit
HTML_DIR = HERE / "html"
TODAY = time.strftime("%Y-%m-%d")

SLIDE_W, SLIDE_H = 1200, 630
NOTE_W, NOTE_H = 800, 600

# ----------------------------------------------------------------- brand

PLACEHOLDER = {  # used only if brand/tokens.json is missing
    "audience": dict(background="#F6F1E8", surface="#FFFFFF", text="#17192A", muted="#6B6F85", accent="#FF6A3D"),
    "presenter": dict(background="#0F1222", surface="#1B1F35", text="#F6F1E8", muted="#A9AEC6", accent="#4FD1B3"),
    "crease": dict(light="rgba(23,25,42,0.12)", dark="rgba(246,241,232,0.14)"),
    "display": '"Charter", Georgia, serif', "text": '"Avenir Next", -apple-system, sans-serif',
    "scale": dict(slideTitle=84, slideStatement=60, slideHeading=44, slideBody=26, uiLabel=17, caption=15),
    "margin": 64, "gutter": 64, "radius": dict(control=8, card=14),
    "source": "placeholder (brand/tokens.json not found)",
}


def load_brand() -> dict:
    tj = BRAND / "tokens.json"
    if not tj.exists():
        print("  brand/tokens.json not found, using placeholder brand")
        return PLACEHOLDER
    t = json.loads(tj.read_text())
    col = t["color"]
    roles = lambda face: {k: col[face][k]["hex"] for k in ("background", "surface", "text", "muted", "accent")}
    disp = t["type"]["display"]
    text = t["type"]["text"]
    return {
        "audience": roles("audience"), "presenter": roles("presenter"),
        "crease": dict(light=col["crease"]["light"], dark=col["crease"]["dark"]),
        "display": f'"{disp["family"]}", {disp.get("fallback", "serif")}',
        "text": f'-apple-system, "{text["family"]} Text", "{text["family"]} Display", "{text["family"]}", Inter, system-ui, sans-serif',
        "scale": t["type"]["scale_canvas1200"],
        "margin": t["space"]["slideMargin_canvas1200"], "gutter": t["space"]["columnGutter_canvas1200"],
        "radius": t["radius"],
        "source": f'brand/tokens.json v{t.get("version", "?")}',
    }


def font_faces() -> str:
    out = []
    for f in sorted((HERE / "fonts").glob("*.ttf")):
        style = "italic" if "italic" in f.name.lower() else "normal"
        fam = re.sub(r"-.*$", "", f.stem)
        fam = re.sub(r"(?<!^)(?=[A-Z])", " ", fam)  # InstrumentSerif -> Instrument Serif
        b64 = base64.b64encode(f.read_bytes()).decode()
        out.append(f'@font-face{{font-family:"{fam}";font-style:{style};font-weight:400;src:url(data:font/ttf;base64,{b64}) format("truetype")}}')
    return "\n".join(out)


def write_brand_css(b: dict) -> str:
    a, p, c, s = b["audience"], b["presenter"], b["crease"], b["scale"]
    css = f"""/* GENERATED by render/build.py from {b['source']} on {TODAY}.
   Edit ../../brand/tokens.json (or the PLACEHOLDER dict in build.py), then re-run render.sh. */
:root {{
  /* audience face (light) */
  --a-bg: {a['background']}; --a-surface: {a['surface']}; --a-text: {a['text']}; --a-muted: {a['muted']}; --a-accent: {a['accent']};
  /* presenter face (dark mirror) */
  --p-bg: {p['background']}; --p-surface: {p['surface']}; --p-text: {p['text']}; --p-muted: {p['muted']}; --p-accent: {p['accent']};
  /* the fold line */
  --crease-light: {c['light']}; --crease-dark: {c['dark']};
  /* type */
  --font-display: {b['display']};
  --font-text: {b['text']};
  --fs-title: {s['slideTitle']}px; --fs-statement: {s['slideStatement']}px; --fs-heading: {s['slideHeading']}px;
  --fs-body: {s['slideBody']}px; --fs-label: {s['uiLabel']}px; --fs-caption: {s['caption']}px;
  /* space and radius */
  --margin: {b['margin']}px; --gutter: {b['gutter']}px;
  --r-control: {b['radius']['control']}px; --r-card: {b['radius']['card']}px;
}}
"""
    (HERE / "brand.css").write_text(css)
    return css


def svg_asset(name: str, fallback: str) -> str:
    f = BRAND / "mark" / name
    if not f.exists():
        return fallback
    s = f.read_text()
    return re.sub(r'\s(width|height)="[^"]*"', "", s, count=2)  # root sizing comes from CSS


FALLBACK_MARK = '<svg viewBox="0 0 100 100"><path d="M50 26 18 70l6.5 4.7L50 39.2l25.5 35.5 6.5-4.7z" fill="currentColor"/></svg>'
MICRO = """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true">
  <rect x="9" y="3" width="6" height="11" rx="3"/><path d="M5 11a7 7 0 0 0 14 0"/><path d="M12 18v3"/></svg>"""

# ----------------------------------------------------------------- chrome

def render(html_path: Path, png_path: Path, w: int, h: int, scale: int = 1, timeout: float = 40) -> None:
    """Screenshot one local HTML file. Chrome does not exit on its own after
    --screenshot on this machine, so poll for a stable PNG and then kill it."""
    png_path.parent.mkdir(parents=True, exist_ok=True)
    if png_path.exists():
        png_path.unlink()
    args = [CHROME, "--headless=new", "--disable-gpu", "--hide-scrollbars", "--no-first-run",
            "--no-default-browser-check", f"--user-data-dir={PROFILE}", f"--window-size={w},{h}",
            f"--force-device-scale-factor={scale}", f"--screenshot={png_path}", f"file://{html_path}"]
    proc = subprocess.Popen(args, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    deadline, last = time.time() + timeout, -1
    while time.time() < deadline:
        if png_path.exists():
            size = png_path.stat().st_size
            if size > 0 and size == last:
                break
            last = size
        time.sleep(0.25)
    subprocess.run(["pkill", "-f", f"user-data-dir={PROFILE}"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        proc.kill()
    if not png_path.exists() or png_path.stat().st_size == 0:
        sys.exit(f"render failed: {html_path}")
    print(f"  {png_path.relative_to(DECK)}")


def esc(s: str) -> str:
    return html.escape(s, quote=False)


def page(title: str, css: str, body: str) -> str:
    return f'<!doctype html><html><head><meta charset="utf-8"><title>{esc(title)}</title><style>{FONTS}{BRAND_CSS}{css}</style></head><body>{body}</body></html>'

# ----------------------------------------------------------------- slide page (brand templates)

SLIDE_CSS = """
html,body{margin:0;width:1200px;height:630px;overflow:hidden;background:var(--a-bg);color:var(--a-text);font-family:var(--font-text);-webkit-font-smoothing:antialiased}
.slide{position:relative;width:1200px;height:630px}
.face{position:absolute;top:0;width:600px;height:630px;box-sizing:border-box;padding:var(--margin);background:var(--a-bg);display:flex;flex-direction:column}
.face.l{left:0}.face.r{left:600px}.face.lit{background:var(--a-surface)}.face.mid{justify-content:center}
.crease{position:absolute;left:599.5px;top:0;width:1px;height:630px;background:var(--crease-light)}
.crease.top{height:170px}.crease.bot{top:456px;height:174px}
.tab{position:absolute;left:598.5px;top:0;width:3px;height:28px;background:var(--a-accent)}
.label{font-size:var(--fs-label);font-weight:500;letter-spacing:.06em;text-transform:uppercase;color:var(--a-muted)}
.spacer{flex:1}
h1.title{font-family:var(--font-display);font-weight:400;font-size:var(--fs-title);line-height:1.04;letter-spacing:-.01em;margin:0}
h1.title.long{font-size:68px}
.statement{font-family:var(--font-display);font-style:italic;font-weight:400;font-size:var(--fs-statement);line-height:1.12;letter-spacing:-.005em;margin:0}
.statement.up{font-style:normal}
h2.heading{font-family:var(--font-display);font-weight:400;font-size:var(--fs-heading);line-height:1.15;margin:16px 0 0}
p.body{font-size:var(--fs-body);line-height:1.4;color:var(--a-text);margin:24px 0 0}
p.body.muted{color:var(--a-muted)}
.num{font-family:var(--font-display);font-size:var(--fs-heading);color:var(--a-muted);line-height:1}
.wordmark{width:430px}.wordmark svg{display:block;width:100%;height:auto}
.markbox{width:56px;height:56px;margin-bottom:20px}.markbox svg{width:100%;height:100%;display:block}
/* two-column: mini presenter card on the private face */
.mini{margin-top:20px;background:var(--p-bg);color:var(--p-text);border-radius:var(--r-card);padding:22px 24px;height:296px;box-sizing:border-box;display:flex;flex-direction:column}
.mini .h{display:flex;justify-content:space-between;align-items:flex-start;font-size:13px;font-weight:500;letter-spacing:.06em;text-transform:uppercase;color:var(--p-muted)}
.mini .h b{font-size:30px;font-weight:500;letter-spacing:0;text-transform:none;color:var(--p-text);font-variant-numeric:tabular-nums;line-height:1}
.mini .n{flex:1;margin-top:18px}.mini .n i{display:block;height:10px;border-radius:5px;background:rgba(154,163,174,.32);margin:0 0 12px}
.mini .f{display:flex;justify-content:space-between;align-items:flex-end}
.mini .f em{font-family:var(--font-display);font-style:italic;font-size:28px;color:var(--p-accent);line-height:1}
.mini .f span{width:96px;height:50px;border-radius:6px;background:var(--a-surface);border:1px solid var(--crease-dark)}
/* live: topic field and three slots */
.field{display:flex;align-items:center;gap:14px;height:66px;border-radius:var(--r-control);background:var(--a-bg);border:1px solid rgba(17,20,24,.18);padding:0 20px;font-size:21px;color:var(--a-muted)}
.field svg{width:26px;height:26px;color:var(--a-accent)}.field i{width:2px;height:26px;background:var(--a-accent);margin-left:-6px}
.ghosts{display:flex;gap:12px;margin-top:16px}
.ghosts div{flex:1;height:82px;border-radius:var(--r-control);border:1.5px dashed rgba(17,20,24,.28);display:flex;align-items:center;justify-content:center;font-size:15px;color:var(--a-muted)}
/* listen: cue pill */
.pill{display:inline-flex;align-items:center;gap:12px;margin-top:32px;padding:12px 20px;border-radius:999px;background:var(--a-bg);border:1px solid rgba(17,20,24,.18);font-size:20px;color:var(--a-muted);align-self:flex-start}
.pill i{display:block;width:10px;height:10px;border-radius:50%;background:var(--a-accent)}.pill em{font-style:normal;color:var(--a-accent)}
/* close: both faces quiet, mark astride the crease, crease interrupted */
.centre{position:absolute;left:0;top:196px;width:1200px;text-align:center}
.centre .markbox{margin:0 auto 26px;width:88px;height:88px}
.centre h2{font-family:var(--font-display);font-weight:400;font-size:56px;line-height:1.15;margin:0}
.centre p{font-size:var(--fs-body);color:var(--a-muted);margin:12px 0 0}
"""


def slide_page(s: dict, idx: int, total: int) -> str:
    layout, title, body, cue = s["layout"], esc(s["title"]), esc(s["body"]), esc(s["cue"])
    crease = '<div class="crease"></div><div class="tab"></div>'
    if layout == "cover":
        if s["title"].strip().lower() == "flipside":
            head = f'<div class="wordmark">{WORDMARK}</div>'
            label = ""
        else:
            long = " long" if len(s["title"]) > 22 else ""
            head = f'<div class="markbox">{MARK}</div><h1 class="title{long}">{title}</h1>'
            label = '<div class="label">Flipside</div>'
        faces = f'<div class="face l lit">{label}<div class="spacer"></div>{head}<p class="body muted">{body}</p></div><div class="face r"></div>'
    elif layout == "statement":
        faces = (f'<div class="face l"><div class="num">{idx:02d}</div></div>'
                 f'<div class="face r lit mid"><p class="statement">{title}</p><p class="body">{body}</p></div>')
    elif layout == "split":
        faces = (f'<div class="face l lit"><div class="label">Public face</div><h2 class="heading">{title}</h2><p class="body">{body}</p></div>'
                 f'<div class="face r lit"><div class="label">Private face</div>'
                 f'<div class="mini"><div class="h"><span>Slide {idx} of {total}</span><b>00:00</b></div>'
                 f'<div class="n"><i style="width:100%"></i><i style="width:76%"></i><i style="width:88%"></i></div>'
                 f'<div class="f"><em>“{cue}”</em><span></span></div></div></div>')
    elif layout == "live":
        faces = (f'<div class="face l lit mid"><p class="statement up">{title}</p><p class="body">{body}</p></div>'
                 f'<div class="face r lit mid"><div class="label" style="margin-bottom:16px">Listening</div>'
                 f'<div class="field">{MICRO}<span>listening for a topic</span><i></i></div>'
                 f'<div class="ghosts"><div>slide 1</div><div>slide 2</div><div>slide 3</div></div></div>')
    elif layout == "listen":
        faces = (f'<div class="face l"><div class="num">{idx:02d}</div></div>'
                 f'<div class="face r lit mid"><p class="statement up">{title}</p><p class="body">{body}</p>'
                 f'<div class="pill"><i></i><span>listening for <em>“{cue}”</em></span></div></div>')
    elif layout == "close":
        crease = '<div class="crease top"></div><div class="crease bot"></div>'
        faces = (f'<div class="face l"></div><div class="face r"></div>'
                 f'<div class="centre"><div class="markbox">{MARK}</div><h2>{title}</h2><p>{body}</p></div>')
    else:
        sys.exit(f"unknown layout {layout!r} on slide {s['id']}")
    return page(s["title"], SLIDE_CSS, f'<div class="slide">{faces}{crease}</div>')

# ----------------------------------------------------------------- notes page (dark mirror)

NOTE_CSS = """
html,body{margin:0;width:800px;height:600px;overflow:hidden;background:var(--p-bg);color:var(--p-text);font-family:var(--font-text);-webkit-font-smoothing:antialiased}
.card{position:relative;height:100%;box-sizing:border-box;padding:32px 36px 30px;display:flex;flex-direction:column}
.head{display:flex;justify-content:space-between;align-items:flex-start}
.lbl{font-size:14px;font-weight:500;letter-spacing:.06em;text-transform:uppercase;color:var(--p-muted)}
.where b{display:block;font-family:var(--font-display);font-weight:400;font-size:26px;color:var(--p-text);margin-top:6px;max-width:480px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.badge{display:inline-block;margin-left:10px;padding:3px 8px;border-radius:4px;background:var(--p-accent);color:var(--p-bg);font-weight:600}
.timer{text-align:right}
.timer b{display:block;font-size:44px;font-weight:500;color:var(--p-text);line-height:1;margin-top:6px;font-variant-numeric:tabular-nums}
.timer b span{color:var(--p-muted);font-size:22px;font-weight:400}
.notes{flex:1;margin-top:26px;font-size:__NOTES_PX__px;line-height:1.4;color:var(--p-text);overflow:hidden}
.foot{display:flex;justify-content:space-between;align-items:flex-end;gap:24px;padding-top:16px;border-top:1px solid var(--crease-dark)}
.cue{flex:1;min-width:0}
.cue b{display:block;font-family:var(--font-display);font-style:italic;font-weight:400;font-size:42px;line-height:1.1;color:var(--p-accent);margin-top:6px}
.next{flex:0 0 240px}.next .lbl{margin-bottom:6px}
.next img,.next .end{display:block;width:240px;height:126px;border-radius:8px;border:1px solid var(--crease-dark);box-sizing:border-box}
.next .end{background:var(--p-surface);color:var(--p-muted);display:flex;align-items:center;justify-content:center;gap:10px;font-size:15px}
.next .end svg{width:28px;height:28px}
.next small{display:block;margin-top:6px;font-size:14px;color:var(--p-muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;width:240px}
"""


def fmt(sec: int) -> str:
    return f"{sec // 60}:{sec % 60:02d}"


def notes_page(s: dict, idx: int, total: int, nxt: dict, fallback: bool) -> str:
    badge = '<span class="badge">Fallback deck</span>' if fallback else ""
    if nxt.get("png"):
        next_html = f'<img src="file://{nxt["png"]}" alt=""><small>{esc(nxt["label"])}</small>'
    else:
        next_html = f'<div class="end">{MARK_DARK}{esc(nxt["label"])}</div><small>{esc(nxt.get("sub", ""))}</small>'
    if s["cue"]:
        cue_html = f'<div class="lbl">Say to advance</div><b>“{esc(s["cue"])}”</b>'
    else:
        cue_html = '<div class="lbl">No cue. To finish</div><b>Fold the phone shut</b>'
    n = len(s["notes"])
    notes_px = 36 if n <= 90 else 32 if n <= 170 else 29 if n <= 280 else 26 if n <= 360 else 24
    body = f"""<div class="card">
<div class="head">
  <div class="where"><span class="lbl">Slide {idx} of {total}</span>{badge}<b>{esc(s["title"])}</b></div>
  <div class="timer"><span class="lbl">Elapsed</span><b>00:00 <span>/ {fmt(s["durationHint"])}</span></b></div>
</div>
<div class="notes">{esc(s["notes"])}</div>
<div class="foot"><div class="cue">{cue_html}</div><div class="next"><div class="lbl">Next</div>{next_html}</div></div>
</div>"""
    return page(f"Notes {idx}", NOTE_CSS.replace("__NOTES_PX__", str(notes_px)), body)

# ----------------------------------------------------------------- contact sheet

def contact_sheet(sections: list, brand_source: str) -> Path:
    cols, gap, margin, thumb_w = 6, 24, 24, 372
    header_h, sec_h, cap_h = 96, 60, 48
    heights = {"slide": round(thumb_w * SLIDE_H / SLIDE_W), "note": round(thumb_w * NOTE_H / NOTE_W)}
    W = margin * 2 + cols * thumb_w + (cols - 1) * gap
    total_h = header_h + margin
    blocks = []
    for heading, items, kind in sections:
        th = heights[kind]
        rows = (len(items) + cols - 1) // cols
        total_h += sec_h + rows * (th + cap_h) + (rows - 1) * gap
        cells = "".join(f'<figure><img src="file://{p}" style="height:{th}px"><figcaption>{esc(c)}</figcaption></figure>' for p, c in items)
        blocks.append(f'<h2>{esc(heading)}</h2><div class="grid">{cells}</div>')
    css = f"""
html,body{{margin:0;background:var(--a-bg);color:var(--a-text);font-family:var(--font-text);width:{W}px;height:{total_h}px;overflow:hidden;-webkit-font-smoothing:antialiased}}
.sheet{{padding:0 {margin}px}}
header{{height:{header_h}px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--crease-light)}}
header h1{{font-family:var(--font-display);font-weight:400;font-size:36px;margin:0}}
header span{{font-size:14px;color:var(--a-muted)}}
h2{{height:{sec_h}px;line-height:{sec_h}px;margin:0;font-size:15px;font-weight:500;letter-spacing:.06em;text-transform:uppercase;color:var(--a-muted)}}
.grid{{display:grid;grid-template-columns:repeat({cols},{thumb_w}px);gap:{gap}px}}
figure{{margin:0;width:{thumb_w}px}}
img{{display:block;width:{thumb_w}px;border-radius:6px;box-sizing:border-box;border:1px solid var(--crease-light);object-fit:cover;background:#fff}}
figcaption{{height:{cap_h}px;padding-top:8px;box-sizing:border-box;font-size:12px;line-height:1.35;color:var(--a-muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}}
"""
    body = f'<div class="sheet"><header><h1>Flipside self-pitch deck &middot; contact sheet</h1><span>{TODAY} &middot; {esc(brand_source)} &middot; render/build.py</span></header>{"".join(blocks)}</div>'
    p = HTML_DIR / "contact-sheet.html"
    p.write_text(page("Contact sheet", css, body))
    out = DECK / "contact-sheet.png"
    render(p, out, W, total_h)
    return out

# ----------------------------------------------------------------- driver

def build_deck(deck, slides_dir, notes_dir, fallback, after_last, live_next=None):
    total = len(deck)
    pngs_1x = []
    for i, s in enumerate(deck, 1):
        name = f"{i:02d}-{s['id']}"
        (HTML_DIR / f"{name}.html").write_text(slide_page(s, i, total))
        out1 = slides_dir / "1200x630" / f"{name}.png"
        render(HTML_DIR / f"{name}.html", out1, SLIDE_W, SLIDE_H, 1)
        pngs_1x.append(out1)
    for i, s in enumerate(deck, 1):
        name = f"{i:02d}-{s['id']}"
        render(HTML_DIR / f"{name}.html", slides_dir / "2400x1260" / f"{name}.png", SLIDE_W, SLIDE_H, 2)
    note_pngs = []
    for i, s in enumerate(deck, 1):
        name = f"{i:02d}-{s['id']}"
        nxt = {"png": pngs_1x[i], "label": f"{i + 1} / {total}  {deck[i]['title']}"} if i < total else after_last
        if live_next and s["layout"] == "live":
            nxt = live_next
        (HTML_DIR / f"notes-{name}.html").write_text(notes_page(s, i, total, nxt, fallback))
        out = notes_dir / "800x600" / f"{name}.png"
        render(HTML_DIR / f"notes-{name}.html", out, NOTE_W, NOTE_H, 1)
        note_pngs.append(out)
    return pngs_1x, note_pngs


def main():
    global FONTS, BRAND_CSS, MARK, MARK_DARK, WORDMARK
    if not Path(CHROME).exists():
        sys.exit("Google Chrome not found at " + CHROME)
    brand = load_brand()
    print(f"brand: {brand['source']}")
    BRAND_CSS = write_brand_css(brand)
    FONTS = font_faces()
    MARK = svg_asset("flipside-mark.svg", FALLBACK_MARK)
    MARK_DARK = svg_asset("flipside-mark-dark.svg", FALLBACK_MARK)
    WORDMARK = svg_asset("flipside-wordmark.svg", FALLBACK_MARK)
    for d in (HTML_DIR, DECK / 'slides', DECK / 'notes', DECK / 'fallback'):
        shutil.rmtree(d, ignore_errors=True)  # no stale PNGs from renamed slides
    HTML_DIR.mkdir(parents=True)
    main_deck = json.loads((DECK / "deck.json").read_text())
    fb_deck = json.loads((DECK / "fallback-deck.json").read_text())

    print("fallback deck")
    fb_slides, fb_notes = build_deck(
        fb_deck, DECK / "fallback" / "slides", DECK / "fallback" / "notes", fallback=True,
        after_last={"png": None, "label": "back to the pitch", "sub": f"{len(main_deck)} / {len(main_deck)}  {main_deck[-1]['title']}"})
    print("main deck")
    slides, notes = build_deck(
        main_deck, DECK / "slides", DECK / "notes", fallback=False,
        after_last={"png": None, "label": "close the phone", "sub": "recap email sends on fold"},
        live_next={"png": fb_slides[0], "label": f"generated deck (fallback shown): {fb_deck[0]['title']}"})

    print("contact sheet")
    def cap(paths, deck):
        return [(p, f"{p.name}   cue: \"{s['cue']}\"   {s['durationHint']}s" if s["cue"] else f"{p.name}   no cue, fold to finish   {s['durationHint']}s")
                for p, s in zip(paths, deck)]
    contact_sheet([
        ("Audience slides  1200x630 (2400x1260 also rendered)", cap(slides, main_deck), "slide"),
        ("Presenter notes cards  800x600", cap(notes, main_deck), "note"),
        ("FALLBACK deck  audience slides", cap(fb_slides, fb_deck), "slide"),
        ("FALLBACK deck  notes cards", cap(fb_notes, fb_deck), "note"),
    ], brand["source"])
    shutil.rmtree(PROFILE, ignore_errors=True)
    print("done")


if __name__ == "__main__":
    main()
